//
//  HomeModels.swift
//  ExVIPDataPassing
//
//  Created by AphiwitSCB on 1/9/2562 BE.
//  Copyright (c) 2562 OnceKB. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home
{
  // MARK: Use cases
  
  enum showText
  {
    struct Request
    {
        var username: String
    }
    struct Response
    {
        var username: String
    }
    struct ViewModel
    {
        var usernameMessage: String
    }
  }
}
