//
//  HomeInteractor.swift
//  ExVIPDataPassing
//
//  Created by AphiwitSCB on 1/9/2562 BE.
//  Copyright (c) 2562 OnceKB. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic
{
    func getShowTextCondition(request: Home.showText.Request)
}

protocol HomeDataStore
{
  var name: String { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore
{
    
    
  var presenter: HomePresentationLogic?
  var worker: HomeWorker?
  var name: String = ""
 
  
    func getShowTextCondition(request: Home.showText.Request) {
        name = request.username
        let response = Home.showText.Response(username: name)
        presenter?.presentShowText(response: response)
    }
}
