//
//  HomeInteractor.swift
//  ExVIPDataPassing
//
//  Created by AphiwitSCB on 1/9/2562 BE.
//  Copyright (c) 2562 OnceKB. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic
{
//  func doSomething(request: Home.Something.Request)
    func getShowTextCondition(request: Home.showText.Request)
}

protocol HomeDataStore
{
  //var name: String { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore
{
    
    
  var presenter: HomePresentationLogic?
  var worker: HomeWorker?
  var name: String = ""
  
  // MARK: Do something
  
 /* func doSomething(request: Home.Something.Request)
  {
    worker = HomeWorker()
    worker?.doSomeWork()
    
    let response = Home.Something.Response()
    presenter?.presentSomething(response: response)
  }*/
    
    func getShowTextCondition(request: Home.showText.Request) {
        let response = Home.showText.Response(username: name)
//        presenter?.presentShowTextInformation(response: response)
        presenter?.presentShowText(response: response)
    }
}
